---
"$schema": http://json-schema.org/draft-04/hyper-schema
title: Config Vars
description: Config Vars allow you to manage the configuration information provided to an app on iruka.
stability: prototype
strictProperties: true
type:
- object
definitions:
  foo:
    description: an example key-value
    example: bar
    readOnly: false
    type:
    - string
  baz:
    description: an example key-value
    example: qux
    readOnly: false
    type:
    - string
links:
- description: Get config-vars for app.
  href: "/apps/{(%2Fschemata%2Fapp%23%2Fdefinitions%2Fidentity)}/config-vars"
  method: GET
  rel: self
  title: Info
- description: Update config-vars for app. You can update existing config-vars by setting them again, and remove by setting it to `\"\"`.
  href: "/apps/{(%2Fschemata%2Fapp%23%2Fdefinitions%2Fidentity)}/config-vars"
  method: PATCH
  rel: update
  schema:
    properties: {
      "FOO": {
        "$ref": "/schemata/config-vars#/definitions/foo"
      },
      "BAZ": {
        "$ref": "/schemata/config-vars#/definitions/baz"
      }
    }
    type:
    - object
  title: Update
properties:
  FOO:
    "$ref": "/schemata/config-vars#/definitions/foo"
  BAZ:
    "$ref": "/schemata/config-vars#/definitions/baz"
  type:
  - object
id: schemata/config-vars
